name:                zero-bullshit
version:             0.1.0.0
github:              "alpacaaa/zero-haskell"
license:             BSD3
author:              "Marco Sampellegrini"
maintainer:          "babbonatale@alpcaaa.net"
copyright:           "2019 Marco Sampellegrini"


ghc-options:
  - -Wall
  - -Werror

synopsis:            A simple and mildly useful webserver library.
category:            Web

description: |
  This Haskell package provides a very simple webserver implementation similar to @express.js@ or @sinatra@.

  It comes as part of the <https://github.com/alpacaaa/zero-bullshit-haskell Zero Bullshit Haskell> project,
  where you can learn Haskell with hands on exercises and bullshit free explanations!

dependencies:
- aeson
- base >= 4.11 && < 5
- bytestring
- containers
- http-types
- random
- scotty
- stm
- text
- wai
- wai-cors

library:
  source-dirs: src
