name:                zero-bullshit
version:             0.1.0.0
github:              "alpacaaa/zero-bullshit-haskell"
license:             BSD3
author:              "Marco Sampellegrini"
maintainer:          "babbonatale@alpcaaa.net"
copyright:           "2019 Marco Sampellegrini"


ghc-options:
  - -Wall
  - -Werror

synopsis:            A simple and mildly useful webserver library.
category:            Web

description: |
  This Haskell package provides a very simple webserver implementation similar to @express.js@ or @sinatra@.

  It comes as part of the <https://github.com/alpacaaa/zero-bullshit-haskell Zero Bullshit Haskell> project,
  where you can learn Haskell with hands on exercises and bullshit free explanations!

  To install this package, add it as an external dependency in your @stack.yaml@ (it's not on Hackage yet).

  > # stack.yaml
  >
  > extra-deps:
  > - github: alpacaaa/zero-bullshit-haskell
  >   commit: master
  >   subdirs:
  >     - library

  And then add @zero-bullshit@ as a dependency in @package.yaml@.

  > # package.yaml
  >
  > dependencies:
  > - base
  > - zero-bullshit

dependencies:
- aeson
- base >= 4.11 && < 5
- bytestring
- containers
- http-types
- random
- scotty
- stm
- text
- wai
- wai-cors

library:
  source-dirs: src
